In [1]:
%matplotlib inline
from ipywidgets import interact, fixed
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('bmh')
import scipy.signal as sg
import scipy.linalg as lg
import scipy.fftpack as fft

In [2]:
def cconv2(x1, x2, N=None):
    from math import ceil
    from scipy.signal import convolve
    # linear convolution
    y = convolve(x1, x2)
    # if N not specified, return full linear convolution 
    if N == None:
        return convolve(x1, x2)
    x1l = x1.shape[0]
    x2l = x2.shape[0]
    S = max(x1l, x2l)
    if N < S:
        raise ValueError('N ({0}) must be at least the largest length of '.format(N) +
                         'x1 ({0}) and x2 ({1})'.format(x1l, x2l))
    M = y.shape[0]
    R = ceil(M/N)
    ye = np.r_[y, [0]*(R*N-M)].reshape((R, N))
    return np.sum(ye, axis=0)


def cconv(x1, x2, N=None):
    import scipy.linalg as lg

    # Como señales sería algo así
    # if N == None:
    #     N = x1.length() + x2.length() - 1
    # r = range(0, N)
    # x1e = x1.compute(r)
    # x2e = x2.compute(r)
    # return x1e.dot(lg.circulant(x2e).T)
    
    # xk.data lengths
    x1l = x1.shape[0]
    x2l = x2.shape[0]
    
    # if N not specified, set large enough 
    if N == None:
        N = x1l+x2l-1

    # force x1.data of length N 
    if x1l >= N:
        x1e = x1[0:N]
    else:
        x1e = np.r_[x1, [0]*(N-x1l)]
    
    # force x2.data of length N 
    x2l = len(x2)
    if x2l >= N:
        x2e = x2[0:N]
    else:
        x2e = np.r_[x2, [0]*(N-x2l)]
    
    # compute circular convolution
    return x1e.dot(lg.circulant(x2e).T)

In [3]:
x1 = np.array([1., 2, 3, 3, 3, 3])
x2 = np.array([1, 2, 3, 4, 5, 6])
N = max(len(x1), len(x2))
N = 13 #len(x1)+len(x2)-1
x3 = cconv2(x1, x2, N)
print(x3)
X1 = fft.fft(x1, N)
X2 = fft.fft(x2, N)
X3 = X1 * X2
x33 = np.real_if_close(fft.ifft(X3, N))
x33[x33 < 100*np.finfo(np.float).eps] = 0
print(x33)
np.allclose(x3, x33)

[  1.   4.  10.  19.  31.  46.  54.  54.  45.  33.  18.   0.   0.]
[  1.   4.  10.  19.  31.  46.  54.  54.  45.  33.  18.   0.   0.]


True

In [4]:
x = np.arange(0, 10)
x1 = np.reshape(x, (5, 2))

In [5]:
np.sum(x1, axis=1)

array([ 1,  5,  9, 13, 17])

In [6]:
x.min()

0

In [7]:
x33

array([  1.,   4.,  10.,  19.,  31.,  46.,  54.,  54.,  45.,  33.,  18.,
         0.,   0.])